use_frameworks!

platform :ios, '10.0'

target 'React-jsinspector_Example' do
  pod 'React-jsinspector', :path => '../'

  target 'React-jsinspector_Tests' do
    inherit! :search_paths

    
  end
end
